# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, blazeHtml, blazeMarkup, clay, filepath, markdown, split
, text
}:

cabal.mkDerivation (self: {
  pname = "maximilian-huber";
  version = "0.1.0.0";
  src = ./.;
  isLibrary = false;
  isExecutable = true;
  buildDepends = [
    blazeHtml blazeMarkup clay filepath markdown split text
  ];
  meta = {
    homepage = "maximilian-huber.de";
    description = "my homepage";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
