resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/21/19.yaml

packages:
- '.'
nix:
  packages: [zlib]
extra-deps:
- clay-0.14.0@sha256:382eced24317f9ed0f7a0a4789cdfc6fc8dd32895cdb0c4ea50a1613bee08af3,2128
flags: {}
extra-package-dbs: []

# In the dependencies for clay-0.14.0:
#    * base must match >=4.11 && <4.16, but base-4.17.2.0 is in the Stack configuration (latest matching version is 4.15.1.0).
#  needed due to maximilian-huber-0.1.0.0 -> clay-0.14.0
allow-newer: true